version: '3.8'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-image
    container_name: ewm-stats
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ./ewm-service
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - STATS_SERVER_URL=http://stats-server:9090
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm